# Generated by Django 4.1.2 on 2023-06-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('farmer', '0004_product_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='farmer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bid_farmer', to='account.userprofile'),
        ),
    ]
