# Generated by Django 4.1.2 on 2024-04-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Locked', 'Locked')], max_length=20),
        ),
    ]
