# Generated by Django 4.1.2 on 2022-10-13 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Patna', 'Patna'), ('Itanagar', 'Itanagar')], max_length=70, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai')], max_length=70, null=True)),
                ('landmark', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Farmer', 'Farmer'), ('Customer', 'Customer')], max_length=10)),
                ('contact_no', models.PositiveIntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
