# Generated by Django 4.1.2 on 2023-07-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('season', models.CharField(choices=[('Kharif', 'Kharif'), ('Whole Year', 'Whole Year'), ('Rabi', 'Rabi'), ('Autumn', 'Autumn'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soil_N', models.IntegerField()),
                ('soil_P', models.IntegerField()),
                ('soil_K', models.IntegerField()),
                ('soil_Ph', models.FloatField()),
                ('soil_moisture', models.IntegerField()),
                ('crops', models.ManyToManyField(to='account.cropdetail')),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_user_profile', to='account.userprofile')),
            ],
        ),
    ]
